# version: '3'
# services:
# # database container
# postgresdb:
#   image: postgres:latest
#   environment:
#   - POSTGRES_DB=ecommerce
#   - POSTGRES_USER=nadeem
#   - POSTGRES_PASSWORD=1464

#   ports:
#       -"5000:5432"
#   volumes:
#       - database:/var/lib/postgresql/data
   

# volumes:
#   database:

# version: '3.9'
# services:
#   postgresdb:
#     image: postgres:latest
#     environment:
#       - POSTGRES_DB=ecommerce
#       - POSTGRES_USER=nadeem
#       - POSTGRES_PASSWORD=1464
#     ports:
#       - "5000:5432"
#     volumes:
#       - database:/var/lib/postgresql/data

#     # web app container
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: nadeem1815/application
#     port:
#       - "3500:3000"
#     environment:
#       - DB_HOST=local
#       - DB_NAME=ecommerce
#       - DB_USER=nadeem
#       - DB_PORT=5000
#     depends_on:
#       - postgresdb
   

# volumes:
#   database:


version: '3.9'
services:
  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=nadeem
      - POSTGRES_PASSWORD=1464
    
    volumes:
      - database:/var/lib/postgresql/data

  web:
    image: web
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgresdb
      - DB_NAME=ecommerce
      - DB_USER=nadeem
      - DB_PASSWORD=1464
      - DB_PORT=5432
    depends_on:
      - postgresdb

    volumes:
      - ./templates:/app/templates

volumes:
  database:
