// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nadeem1815/premium-watch/pkg/api"
	"github.com/nadeem1815/premium-watch/pkg/api/handler"
	"github.com/nadeem1815/premium-watch/pkg/config"
	"github.com/nadeem1815/premium-watch/pkg/db"
	"github.com/nadeem1815/premium-watch/pkg/repository"
	"github.com/nadeem1815/premium-watch/pkg/usecase"
)

// Injectors from wire.go:

func InitializerAPI(cfg config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	adminRepository := repository.NewAdminRepository(gormDB)
	adminUseCase := usecase.NewAdminUseCase(adminRepository)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	productRepository := repository.NewProductRepository(gormDB)
	productUseCase := usecase.NewProductUseCase(productRepository)
	productHandler := handler.NewProductHandler(productUseCase)
	cartRepository := repository.NewCartRepository(gormDB)
	cartUseCase := usecase.NewCartUseCase(cartRepository)
	cartHandler := handler.NewCartHandler(cartUseCase)
	orderRepoitory := repository.NewOrderRepository(gormDB)
	orderUseCase := usecase.NewOrderUseCase(orderRepoitory, userRepository, productRepository)
	orderHandler := handler.NewOrderHandler(orderUseCase)
	serverHTTP := api.NewServerHTTP(userHandler, adminHandler, productHandler, cartHandler, orderHandler)
	return serverHTTP, nil
}
